package com.WildAmazing.marinating.Demigods.Utilities;

import java.io.Serializable;

public enum Divine implements Serializable {
	APHRODITE, APOLLO, ARES, ARTEMIS, ATHENA, DEMETER, DIONYSUS, HADES, HEPHAESTUS,
	HERA, HERMES, HESTIA, POSEIDON, ZEUS, HYPERION, LAPETUS, COEUS, CRIUS, CRONUS,
	MNEMOSYNE, OCEANUS, PHOEBE, RHEA, TETHYS, THEIA, THEMIS, ATLAS, AURA, DIONE, EOS, HELIOS,
	METIS, OPHION, PERSES, SELENE, STYX, TYPHON, TALOS, CERBERUS, CHARON, EREBOS, MORPHEUS,
	NEMESIS, NIKE, NYX, PROTEUS, PAN, OMNI, PROMETHEUS, GOD, TITAN
}

