name: Demigods
main: com.WildAmazing.marinating.Demigods.Demigods
version: 2.3
description: Ally yourself with mythical deities and battle in the name of the Gods or Titans.
author: marinating, Clashnia
softdepend: [WorldGuard, WorldEdit, Factions]
commands:
    dg:
        description: Important information.
        aliases: demigods
    check:
        description: About the player.
    claim:
        description: Used to claim deities.
    alliance:
        description: Used to toggle alliance chat.
        usage: /alliance
    perks:
        description: Used to modify Perks.
    checkplayer:
        description: View information about another player.
        usage: /checkplayer <player>
        permission: demigods.checkplayer
    getfavor:
        description: Console command to get a player's Favor.
        usage: getfavor <player>
    getdevotion:
        description: Console command to get a player's devotion.
        usage: getlevel <player> or getlevel <player> <deity>
    getascensions:
        description: Console command to get a player's ascensions.
        usage: getascensions <player>
    getmaxfavor:
        description: Console command to get a player's max Favor.
        usage: getmaxfavor <player>
    addmaxfavor:
        description: Console command to add to a player's max Favor.
        usage: addmaxfavor <player> <amount>
    addfavor:
        description: Console command to add to a player's Favor.
        usage: addfavor <player> <amount>
    addunclaimeddevotion:
        description: Console command to give a player unclaimed Devotion.
        usage: addunclaimeddevotion <player> <amount>
    adddevotion:
        description: Console command to add to a player's level.
        usage: adddevotion <player> <deity> <amount>
    addhp:
        description: Console command to recharge a players' hp.
        usage: addhp <player> <amount>
    addascensions:
        description: Console command to add to a player's ascensions.
        usage: addascensions <player> <amount>
    debugplayer:
        description: Console command to debug player files.
        usage: debugplayer <player> <print|write|load>
    givedeity:
        description: Gives a deity to a player.
        usage: /givedeity <player> <deity>
        permission: demigods.givedeity
    removedeity:
        description: Removes a deity from a player.
        usage: /removedeity <player> <deity>
        permission: demigods.removedeity
    forsake:
        description: Remove a deity from a player.
        usage: /forsake <deity>
        permission: demigods.forsake
    setfavor:
        description: Set a player's favor.
        usage: /setfavor <player> <amount>
        permission: demigods.setfavor
    setmaxfavor:
        description: Set a player's favor cap.
        usage: /setfavor <player> <amount>
        permission: demigods.setfavor
    sethp:
        description: Set a player's HP.
        usage: /sethp <player> <amount>
        permission: demigods.sethp
    setmaxhp:
        description: Set a player's max HP.
        usage: /setmaxhp <player> <amount>
        permission: demigods.setmaxhp
    setallegiance:
        description: Manually set a player's allegiance.
        usage: /setallegiance <player> <allegiance>
        aliases: setalliance
        permission: demigods.setalliance
    setdevotion:
        description: Set a player's devotion for a deity.
        usage: /setdevotion <player> <deity> <amount>
        permission: demigods.setdevotion
    getdevotion:
        description: get a player's devotion for a deity.
        usage: /getdevotion <player> <deity>
        permission: demigods.getdevotion
    setascensions:
        description: Set a player's ascensions.
        usage: /setascensions <player> <level>
        permission: demigods.setascensions
    setkills:
        description: Set a player's kills.
        usage: /setkills <player> <kills>
        permission: demigods.setkills
    setdeaths:
        description: Set a player's deaths.
        usage: /setdeaths <player> <deaths>
        permission: demigods.setdeaths
    removeplayer:
        usage: /removeplayer <player>
        description: Removes a player from the save.
        permission: demigods.removeplayer
    bindings:
        usage: /bindings
        description: Display what Materials are used for bindings.
        permission: demigods.bindings
    shrine:
        description: Gives information about shrines.
    shrinewarp:
        usage: /shrinewarp <deity> or /shrinewarp <player> <deity> or /shrinewarp <shrine name>
        description: Warps the user to the shrine.
        permission: demigods.shrinewarp
        alias: warpshrine
    shrineowner:
        usage: /shrineowner add <name> or /shrineowner remove <name> or /shrineowner set <name>  
        description: Gives information about shrines.
        permission: demigods.shrineowner
    removeshrine:
        usage: /removeshrine
        description: Removes a shrine from the save.
        permission: demigods.removeshrine
    listshrines:
        usage: /listshrines
        description: Lists every shrine on the server.
        permission: demigods.listshrines
    fixshrine:
        usage: /fixshrine
        description: Fixes a shrine if the block is missing.
    nameshrine:
        usage: /nameshrine <new name>
        description: Renames an existing shrine.
        permission: demigods.nameshrine
        alias: shrinename
    value:
        description: See Favor value of item in hand.
    shove:
        description: One of Zeus's abilities.
    lightning:
        description: One of Zeus's abilities.
    storm:
        description: Zeus's ultimate.
    strike:
        description: One of Ares' abilities.
    bloodthirst:
        description: One of Ares' abilities.
    crash:
        description: Ares' ultimate.
    cleave:
        description: One of Cronus's abilities.
    slow:
        description: One of Cronus's abilities.
    timestop:
        description: Cronus's ultimate.
    fireball:
        description: One of Prometheus's abilities.
    blaze:
        description: One of Prometheus's abilities.
    firestorm:
        description: Prometheus's ultimate.
    poison:
        description: One of Rhea's abilities.
    plant:
        description: One of Rhea's abilities.
    detonate:
        description: One of Rhea's abilities.
    entangle:
        description: Rhea's ultimate.
    chain:
        description: One of Hades' abilities.
    entomb:
        description: One of Hades' abilities.
    tartarus:
        description: Hades' ultimate.
    reel:
        description: One of Poseidon's abilities.
    drown:
        description: One of Poseidon's abilities.
    waterfall:
        description: Poseidon's ultimate.
    unburden:
        description: One of Atlas' abilities.
    invincible:
        description: Atlas' ultimate.
    flash:
        description: One of Athena's abilities.
    ceasefire:
        description: Athena's ultimate.
    squid:
        description: One of Oceanus' abilities.
    makeitrain:
        description: Oceanus' ultimate.
    starfall:
        description: One of Hyperion's abilities.
    smite:
        description: Hyperion's ultimate.
    reforge:
        description: One of Hephaestus's abilities.
    shatter:
        description: Hephaestus's ultimate.
    cure:
        description: One of Apollo's abilities.
    finale:
        description: Apollo's ultimate.
    swap:
        description: One of Themis' abilities.
    congregate:
        description: Themis' ultimate.
    assemble:
        description: Used with Themis' ultimate.